# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       android-tools

# >> macros
# << macros

Summary:    Minimal set of android tools
Version:    4.2.2_git20130218
Release:    15
Group:      Tools
License:    Apache 2.0
Source0:    android-tools-4.2.2_git20130218.tar.gz
Source1:    adb.mk
Source2:    fastboot.mk
Source3:    mkbootimg.mk
Source100:  android-tools.yaml
Patch0:     0001-Ignore-selinux-android.h.patch
Patch1:     0002-Original-split_bootimg.pl-from-http-www.enck.org-too.patch
Patch2:     0003-Provide-command-line-to-use-mkbootimg-to-recreate-th.patch
Patch3:     0004-Add-mer-android-chroot-to-enter-the-ubu-chroot-from-.patch
Patch4:     0005-Added-libmincrypt-for-building-mkbootimg.patch
Patch5:     0006-Require-r-option-Fix-broken-mount-for-HOME-in-some-i.patch
Patch6:     0007-Add-support-for-.mersdkubu.profile.patch
Patch7:     0008-Support-multiple-chroot-entry-invocation-to-support-.patch
Patch8:     0009-Added-latest-ubuntu-14.04-support-to-debian-version-.patch
Patch9:     0010-ubu-chroot-Fix-broken-exec-handling-and-be-quiet-by-.patch
Patch10:     0011-Mount-home-using-rbind-to-include-any-submounts.patch
Patch11:     0012-Update-to-newer-core-8032f3b.patch
Patch12:     0013-Update-to-new-extras-ba2a236.patch
Patch13:     0014-PATCH-Add-usb-vendor-info.patch
Patch14:     0015-PATCH-Use-mmap-for-fastboot-data.patch
Patch15:     0016-PATCH-Ignore-selinux-android-header.patch
Patch16:     0017-Fixed-the-script-for-non-Bash-users.patch
Patch17:     0018-ubu-chroot-Let-environment-know-we-are-within-the-ub.patch
Patch18:     0019-ubu-chroot-Fix-crash-with-util-linux-2.27.-Fixes-JB-.patch
BuildRequires:  pkgconfig(openssl)
BuildRequires:  libselinux-devel
BuildRequires:  python
BuildRequires:  zlib

%description
android-tools for Mer

The upstream tarball is based of these upstream Android git repos:
  git clone https://android.googlesource.com/platform/system/core
  git clone https://android.googlesource.com/platform/system/extras

with unneeded files removed.

Based on Debian android-tools package


%package -n sudo-for-abuild
Summary:    Install this to allow OBS abuild user to use sudo in build
Group:      Development
Requires:   %{name} = %{version}-%{release}
Requires:   sudo

%description -n sudo-for-abuild
Allow abuild user to execute sudo in an OBS build root.

%prep
%setup -q -n src

# 0001-Ignore-selinux-android.h.patch
%patch0 -p1
# 0002-Original-split_bootimg.pl-from-http-www.enck.org-too.patch
%patch1 -p1
# 0003-Provide-command-line-to-use-mkbootimg-to-recreate-th.patch
%patch2 -p1
# 0004-Add-mer-android-chroot-to-enter-the-ubu-chroot-from-.patch
%patch3 -p1
# 0005-Added-libmincrypt-for-building-mkbootimg.patch
%patch4 -p1
# 0006-Require-r-option-Fix-broken-mount-for-HOME-in-some-i.patch
%patch5 -p1
# 0007-Add-support-for-.mersdkubu.profile.patch
%patch6 -p1
# 0008-Support-multiple-chroot-entry-invocation-to-support-.patch
%patch7 -p1
# 0009-Added-latest-ubuntu-14.04-support-to-debian-version-.patch
%patch8 -p1
# 0010-ubu-chroot-Fix-broken-exec-handling-and-be-quiet-by-.patch
%patch9 -p1
# 0011-Mount-home-using-rbind-to-include-any-submounts.patch
%patch10 -p1
# 0012-Update-to-newer-core-8032f3b.patch
%patch11 -p1
# 0013-Update-to-new-extras-ba2a236.patch
%patch12 -p1
# 0014-PATCH-Add-usb-vendor-info.patch
%patch13 -p1
# 0015-PATCH-Use-mmap-for-fastboot-data.patch
%patch14 -p1
# 0016-PATCH-Ignore-selinux-android-header.patch
%patch15 -p1
# 0017-Fixed-the-script-for-non-Bash-users.patch
%patch16 -p1
# 0018-ubu-chroot-Let-environment-know-we-are-within-the-ub.patch
%patch17 -p1
# 0019-ubu-chroot-Fix-crash-with-util-linux-2.27.-Fixes-JB-.patch
%patch18 -p1

# >> setup
# << setup

%build
# >> build pre
make -f %{SOURCE1} -C core/adb
make -f %{SOURCE2} -C core/fastboot
make -f %{SOURCE3} -C core/mkbootimg
#make -f `pwd`/ext4_utils.mk -C extras/ext4_utils
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
install -D -m 755  core/adb/adb %{buildroot}%{_bindir}/adb
install -D -m 755  core/fastboot/fastboot %{buildroot}%{_bindir}/fastboot
install -D -m 755  core/mkbootimg/mkbootimg %{buildroot}%{_bindir}/mkbootimg
install -D -m 755  split_bootimg.pl %{buildroot}%{_bindir}/split_bootimg
install -D -m 755  mer-android-chroot %{buildroot}%{_bindir}/ubu-chroot
install -D -m 755  mer-ubusdk-bash-setup %{buildroot}%{_datadir}/ubu-chroot/mer-ubusdk-bash-setup
# For sudo-for-abuild
install -D -m 755  sudoers.abuild %{buildroot}%{_sysconfdir}/sudoers.d/abuild

# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}/adb
%{_bindir}/fastboot
%{_bindir}/split_bootimg
%{_bindir}/mkbootimg
%{_bindir}/ubu-chroot
%{_datadir}/ubu-chroot/*
# >> files
# << files

%files -n sudo-for-abuild
%defattr(-,root,root,-)
%{_sysconfdir}/sudoers.d/abuild
# >> files sudo-for-abuild
# << files sudo-for-abuild
